services:
  db:
    image: postgres:16-alpine
    ports:
      - 5682:5432
    environment:
      POSTGRES_DB: rp
      POSTGRES_USER: rp
      POSTGRES_PASSWORD: rp
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
